services:
  php-apache-environment:
    container_name: php-apache
    image: php:7.4-apache
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: husin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
